import { promises as fs } from 'fs'
import path from 'path'
import { Cli as KyselyCodeGenCli, type Config } from 'kysely-codegen'
import openApiToTypeScript, { astToString } from 'openapi-typescript'
import * as prettier from 'prettier'

import { logger } from './helpers'

const generatedFileHeader = `/* eslint-disable -- autogenerated code */\n\n`

/** Add file header and format with prettier */
const formatGeneratedFile = async (outFile: string) => {
  const start = Date.now()
  logger.info('formatting generated file...')
  const content = await fs.readFile(outFile, 'utf8')
  const config = await prettier.resolveConfig(outFile)
  const formattedContent = await prettier.format(generatedFileHeader + content, {
    ...config,
    parser: 'typescript',
  })
  await fs.writeFile(outFile, formattedContent)
  logger.success(`formatted ${outFile} in ${Date.now() - start}ms\n`)
}

/** Introspect database types and write to file */
export const runKyselyCodegen = async (
  dbUrl: string,
  destFile: string,
  options?: Partial<Config> & { replace?: [RegExp, string] },
) => {
  const outFile = options?.outFile ?? path.join(import.meta.dirname, destFile)
  await new KyselyCodeGenCli().generate({
    url: dbUrl,
    outFile,
    excludePattern: options?.excludePattern ?? 'migrations*',
    includePattern: options?.includePattern,
    camelCase: options?.camelCase ?? false,
    dialect: options?.dialect ?? 'postgres',
    envFile: options?.envFile,
    logLevel: options?.logLevel ?? 'warn',
    print: options?.print ?? false,
    defaultSchemas: options?.defaultSchemas,
    typeOnlyImports: options?.typeOnlyImports ?? true,
    verify: options?.verify ?? false,
  })
  let content = await fs.readFile(outFile, 'utf8')
  content = content.replace(/^export interface DB\b/m, 'export interface DbTypes')
  if (options?.replace) {
    const [search, replace] = options.replace
    content = content.replace(search, replace)
  }
  await fs.writeFile(outFile, content)
  await formatGeneratedFile(outFile)
}

/**
 * Generate TypeScript types from an OpenAPI schema and write them to file.
 *
 * @param schema - the OpenAPI document: a parsed object, a raw string, or a
 *   `URL` / file path pointing at a local or remote spec
 * @param destFile - output path, relative to this scripts directory
 */
export const runOpenApiTypegen = async (
  schema: Parameters<typeof openApiToTypeScript>[0],
  destFile: string,
) => {
  const start = Date.now()
  logger.info('converting OpenAPI spec to TypeScript...')
  const generatedTypeScriptString = astToString(
    await openApiToTypeScript(schema, { emptyObjectsUnknown: true, defaultNonNullable: false }),
  )
  const outFile = path.join(import.meta.dirname, destFile)
  await fs.writeFile(outFile, generatedTypeScriptString)
  logger.success(`generated ${destFile} in ${Date.now() - start}ms\n`)
  await formatGeneratedFile(outFile)
}
